import{a as S,S as L,i}from"./assets/vendor-hwdYKDic.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function t(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(o){if(o.ep)return;o.ep=!0;const n=t(o);fetch(o.href,n)}})();const w="45378122-3aa1f0accb7d59cfaae2c348a",q="https://pixabay.com/api/";async function m(r,e=1){try{return(await S.get(q,{params:{key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})).data}catch(t){throw console.error("Error in requestSending:",t.message),new Error(`HTTP error! ${t.message}`)}}function v(){const r=document.querySelector("main"),e=document.createElement("form");e.className="search-image-form";const t=document.createElement("input");t.type="text",t.name="field",t.className="search-field",t.placeholder="Search images...",e.appendChild(t);const s=document.createElement("button");s.textContent="Search",s.type="submit",s.className="submit-button",e.appendChild(s),r.prepend(e)}function y(r){const e=document.querySelector(".gallery"),t=r.map(o=>`
    <li>
    
      <a href="${o.largeImageURL}" title="${o.tags}">
        <img src="${o.webformatURL}" alt="${o.tags}" />  
      </a>
       <div class="gallery-info">
        <p class="gallery-info-item"><b>Likes:</b> ${o.likes}</p>
        <p class="gallery-info-item"><b>Views:</b> ${o.views}</p>
        <p class="gallery-info-item"><b>Comments:</b> ${o.comments}</p>
        <p class="gallery-info-item"><b>Downloads:</b> ${o.downloads}</p>
      </div>
    </li>
  `).join("");e.insertAdjacentHTML("beforeend",t),new L(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function E(){const r=document.querySelector(".gallery"),e=document.createElement("button");e.textContent="Load more",e.type="button",e.className="submit-button load-more-button",e.style.display="none";const t=document.createElement("div");t.className="loader",t.style.display="none",r.insertAdjacentElement("afterend",e),e.insertAdjacentElement("afterend",t)}v();E();const B=document.querySelector(".search-image-form"),u=document.querySelector(".search-field"),x=document.querySelector(".gallery"),f=document.querySelector(".loader"),d=5;let a=1,p="";function h(){f.style.display="block"}function g(){f.style.display="none"}function b(){const r=document.querySelector(".load-more-button");r&&(r.style.display="block")}function l(){const r=document.querySelector(".load-more-button");r&&(r.style.display="none")}function M(){const r=document.querySelector(".gallery li");if(r){const t=2*r.getBoundingClientRect().height;window.scrollBy({top:t,behavior:"smooth"})}}B.addEventListener("submit",async r=>{r.preventDefault();const e=u.value.trim();if(e){p=e,a=1,x.innerHTML="",l(),h();try{const t=await m(e,a);if(t.hits.length===0)throw new Error("No results found");y(t.hits),M(),t.totalHits>a*15?b():i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",class:"info-toast",timeout:4e3})}catch{i.error({message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight",class:"error-toast",timeout:4e3})}finally{g()}u.value=""}});const N=document.querySelector(".load-more-button");N.addEventListener("click",async()=>{if(a>=d){l(),i.info({message:"We're sorry, but you've reached the end of search results (test mode).",position:"topRight",class:"info-toast",timeout:4e3});return}a+=1,h(),l();try{const r=await m(p,a);y(r.hits),r.totalHits<=a*15||a>=d?(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",class:"info-toast",timeout:4e3})):b()}catch{i.error({message:"An error occurred while loading more images. Please try again.",position:"topRight",class:"error-toast",timeout:4e3})}finally{g()}});
//# sourceMappingURL=index.js.map
