import{a as L,S,i}from"./assets/vendor-hwdYKDic.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();const w="45378122-3aa1f0accb7d59cfaae2c348a",q="https://pixabay.com/api/";async function m(r,t=1){try{return(await L.get(q,{params:{key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}catch(o){throw console.error("Error in requestSending:",o.message),new Error(`HTTP error! ${o.message}`)}}function E(){const r=document.querySelector("main"),t=document.createElement("form");t.className="search-image-form";const o=document.createElement("input");o.type="text",o.name="field",o.className="search-field",o.placeholder="Search images...",t.appendChild(o);const s=document.createElement("button");s.textContent="Search",s.type="submit",s.className="submit-button",t.appendChild(s),r.prepend(t)}function f(r){const t=document.querySelector(".gallery"),o=r.map(e=>`
    <li>
    
      <a href="${e.largeImageURL}" title="${e.tags}">
        <img src="${e.webformatURL}" alt="${e.tags}" />  
      </a>
       <div class="gallery-info">
        <p class="gallery-info-item"><b>Likes:</b> ${e.likes}</p>
        <p class="gallery-info-item"><b>Views:</b> ${e.views}</p>
        <p class="gallery-info-item"><b>Comments:</b> ${e.comments}</p>
        <p class="gallery-info-item"><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </li>
  `).join("");t.insertAdjacentHTML("beforeend",o),new S(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function v(){const r=document.querySelector(".gallery"),t=document.createElement("button");t.textContent="Load more",t.type="button",t.className="submit-button load-more-button",t.style.display="none";const o=document.createElement("div");o.className="loader",o.style.display="none",r.insertAdjacentElement("afterend",t),t.insertAdjacentElement("afterend",o)}E();v();const M=document.querySelector(".search-image-form"),u=document.querySelector(".search-field"),x=document.querySelector(".gallery"),y=document.querySelector(".loader"),d=2;let a=1,p="";function h(){y.style.display="block"}function g(){y.style.display="none"}function b(){const r=document.querySelector(".load-more-button");r&&(r.style.display="block")}function c(){const r=document.querySelector(".load-more-button");r&&(r.style.display="none")}M.addEventListener("submit",async r=>{r.preventDefault();const t=u.value.trim();if(t){p=t,a=1,x.innerHTML="",c(),h();try{const o=await m(t,a);if(o.hits.length===0)throw new Error("No results found");f(o.hits),o.totalHits>a*15?b():i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",class:"info-toast",timeout:4e3})}catch{i.error({message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight",class:"error-toast",timeout:4e3})}finally{g()}u.value=""}});const B=document.querySelector(".load-more-button");B.addEventListener("click",async()=>{if(a>=d){c(),i.info({message:"We're sorry, but you've reached the end of search results (test mode).",position:"topRight",class:"info-toast",timeout:4e3});return}a+=1,h(),c();try{const r=await m(p,a);f(r.hits),r.totalHits<=a*15||a>=d?(c(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",class:"info-toast",timeout:4e3})):b()}catch{i.error({message:"An error occurred while loading more images. Please try again.",position:"topRight",class:"error-toast",timeout:4e3})}finally{g()}});
//# sourceMappingURL=index.js.map
